#!/bin/bash

source $HOME/.bashrc
basedir=$HOME/TimeDomainTHz
rundir=/bigdata/fwke/lehnertu/TimeDomainTHz

module load gcc
module load hdf5

cd $rundir
$basedir/build/PropagateStraight Tilted_2001x51.h5

